- project:
    templates:
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - release-notes-jobs
      - periodic-stable-jobs
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
        - openstack-tox-pylint:
            voting: false
        - manila-tox-genconfig
    gate:
      queue: manila
      jobs:
        - manila-tox-genconfig
    post:
      jobs:
        - openstack-tox-cover

- job:
    name: manila-tox-genconfig
    parent: openstack-tox
    description: |
      Run tests for manila project.

      Uses tox with the ``genconfig`` environment.
    vars:
      tox_envlist: genconfig
